[template.environment]
  GQL_HOST = "https://store.lumeandloom.co.uk/graphql"
  NUXT_IMAGE_DOMAINS = "https://store.lumeandloom.co.uk"

[build]
  command = "nuxt generate"

[images]
  remote_images = ["https://store.lumeandloom.co.uk/.*"]
